import type { Metadata } from "next";
import "./globals.css";
import { CustomPointerProvider } from "@/providers/custom-pointer-provider";
import { ScrollProgressProvider } from "@/providers/scroll-progress-provider";

export const metadata: Metadata = {
  title: "Marketopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden scroll-smooth relative">
        <ScrollProgressProvider className="top-[65px]" />
        <CustomPointerProvider />
        {children}
      </body>
    </html>
  );
}
